config/routes.rb
Rails.application.routes.draw do
  get "mapquest_search/create"
  devise_for :users, skip: :registrations

  root to: redirect("/trips")
  # devise_scope :user do
  #   authenticated :user do
  #     root to: redirect("/trips")
  #   end

  #   unauthenticated do
  #     root "devise/sessions#new"
  #   end
  # end

  resources :trips do
    resources :places, only: [:new, :create]
  end
  resources :places, only: [:show, :edit, :update, :destroy]

  namespace :api do
    resources :trips, only: [:index]
  end
  get "search", to: "mapquest#search", as: "mapquest_search"
  get "reverse", to: "mapquest#reverse", as: "mapquest_reverse"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/osm_place.rb
class OsmPlace < ActiveRecord::Base
  has_many :places

  def sync
    first_osm_type = osm_type&.first
    formatted_osm_type = first_osm_type&.capitalize
    fresh_data = MapquestService.new.reverse({osm_id: osm_id, osm_type: formatted_osm_type})
    new_attrs = {
      osm_api_place_id: fresh_data[:place_id],
      osm_type: fresh_data[:osm_type],
      osm_id: fresh_data[:osm_id],
      boundingbox: create_geometry_from_bounding_box(bounding_box: fresh_data[:boundingbox]),
      lonlat: "POINT(#{fresh_data[:lon]} #{fresh_data[:lat]})",
      display_name: fresh_data[:display_name],
      name: fresh_data[:name],
      osm_class: fresh_data[:class],
      tipe: fresh_data[:type],
      address: fresh_data[:address],
      place_rank: fresh_data[:place_rank],
      category: fresh_data[:category],
      addresstype: fresh_data[:addresstype],
      importance: fresh_data[:importance],
      geojson: fresh_data[:geojson]
    }

    update(new_attrs)
  end

  def point
    [lonlat.lon, lonlat.lat]
  end

  private

  def create_geometry_from_bounding_box(bounding_box:)
    south_lat, north_lat, west_lon, east_lon = bounding_box
    factory = RGeo::Geographic.spherical_factory
    sw = factory.point(west_lon, south_lat)
    ne = factory.point(east_lon, north_lat)
    RGeo::Cartesian::BoundingBox.create_from_points(sw, ne).to_geometry
  end
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :trip, optional: true
  belongs_to :osm_place, optional: true
  delegate :point, to: :osm_place, allow_nil: true
  has_many :users, through: :trips

  validates_presence_of :name, message: "can't be blank"
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :places, dependent: :destroy
  has_many :osm_places, through: :places

  validates_presence_of :title, messsage: "can't be blank"

  def start_date
    places.where.not(start_date: nil).order(start_date: :asc).pluck(:start_date).first
  end

  def end_date
    places.where.not(end_date: nil).order(end_date: :desc).pluck(:end_date).first
  end

  def points
    places.where.not(osm_place_id: nil).map do |place|
      lonlat = place.osm_place.lonlat
      [lonlat.lon, lonlat.lat]
    end
  end

  def center
    bounding_box = RGeo::Cartesian::BoundingBox.new(RGeo::Cartesian.simple_factory)
    points = places.where.not(osm_place_id: nil).map { |p| p.osm_place.lonlat }
    points.each { |p| bounding_box.add(p) }
    [bounding_box.center_x, bounding_box.center_y]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :confirmable

  has_and_belongs_to_many :trips
  has_many :places, through: :trips
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ActionController::API
    respond_to :json
  end
end

app/controllers/api/trips_controller.rb
module Api
  class TripsController < ApiController
    def index
      trips = Trip.all.map { |trip|
        TripPresenter.new(trip).to_h
      }

      render json: {
        trips: trips
      }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render react_component: "App"
  end
end

app/controllers/mapquest_controller.rb
class MapquestController < ApplicationController
  before_action :authenticate_user!
  respond_to :json

  def search
    @places = mapquest.search(q: params[:q], addressdetails: 1)

    render json: @places
  end

  def reverse
    @places = mapquest.reverse(lat: params[:lat], lon: params[:lon])

    render json: @places
  end

  private

  def mapquest
    @mapquest ||= MapquestService.new
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: [:create, :new]
  before_action :set_place, only: [:show, :edit, :destroy, :update]

  def new
    @place = @trip.places.new
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @place = @trip.places.new(place_params)

    if params[:place][:osm_id].present?
      osm_place = OsmPlace.find_or_create_by(osm_id: params[:place][:osm_id],
                                             osm_type: params[:place][:osm_type])

      osm_place.sync
      @place.osm_place = osm_place
    end

    respond_to do |format|
      if @place.save
        format.json { render json: {place: @place, url: "/places/#{@place.id}"}, status: :created }
      else
        format.json { render json: {errors: @place.errors}, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    trip = @place.trip

    respond_to do |format|
      if @place.destroy
        format.html { redirect_to trip, notice: "Place was successfully deleted." }
        format.json { render :show, status: :ok, location: trip }
      else
        format.html { render :show }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:start_date, :end_date, :note, :name)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = current_user.trips.map { |trip|
      TripPresenter.new(trip).to_h
    }
  end

  def show
    @presented_trip = TripPresenter.new(@trip).to_h
  end

  def new
    @trip = Trip.new
  end

  def edit
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.users << current_user

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_trip
    @trip = current_user.trips.includes(:places).find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link href="https://fonts.googleapis.com/css?family=Alata&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="app">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato|Source+Sans+Pro" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <div class="devise-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: [trip, place], id: "new_place_form", local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <%= form.hidden_field :osm_id, id: "place_osm_id" %>
    <%= form.hidden_field :osm_type, id: "place_osm_type" %>
    <%= form.hidden_field :osm_display_name, id: "place_osm_display_name" %>

    <div>
      <%= form.text_field :name, placeholder: 'Name' %>
    </div>

    <div>
      <%= form.label :start_date, "Start Date" %>
      <%= form.date_field :start_date %>
    </div>

    <div>
      <%= form.label :end_date, "End Date" %>
      <%= form.date_field :end_date %>
    </div>
  </div>

  <div>
    <%= form.hidden_field :note, id: "place_note" %>
    <trix-editor input="place_note" class="trix-content" placeholder="Note"></trix-editor>
  </div>
  <br>
  <div>
    <div class="actions">
      <%= form.submit  %>
    </div>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>
  Edit
  <%= link_to 'Cancel', place_path(@place) %>
</h1>
<%= render 'form', trip: @trip, place: @place %>
<%= link_to 'Delete', place_path(@place), method: :delete, data: { confirm: "Are you sure you want to delete this Place?\nYou will lose all of the data associated with it." } %>

app/views/places/edit.js.erb
$('.alert-container')
  .html("<%= escape_javascript (render partial: 'shared/dismissable_alert',
                                        locals: { message: @place.errors.full_messages.join(',') } ) %>")

app/views/places/new.html.erb
<%= react_component("PlaceForm") %>

app/views/places/show.html.erb
<% @date = [@place.start_date&.strftime('%A, %d %b %Y'), @place.end_date&.strftime('%A, %d %b %Y')].compact.join(' - ') %>
<%= react_component("Place", name: @place.name,
                             date: @date,
                             note: raw(@place.note),
                             point: @place.point) %>

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div>
      <%= form.text_field :title, placeholder: "Title" %>
    </div>
  </div>

  <div>
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/trips/_list_group.html.erb
<ul class="list-group">
  <% models.each do |model| %>
    <%= link_to model, class: "list-group-item list-group-item-action flex-column align-items-start" do %>
      <h5 class="mb-1"><%= model.try(:title) || model.try(:name) %></h5>
      <small class="d-flex justify-content-between">
        <%= [model.start_date&.strftime("%b %e, %Y"), model.end_date&.strftime("%b %e, %Y")].compact.join(' - ') %>
        <% osm_place_method = model.is_a?(Trip) ? :osm_places : :osm_place %>
        <% if model.public_send(osm_place_method).present? %>
          <i class="fas fa-globe-americas"></i>
        <% end %>
      </small>
    <% end %>
  <% end %>
</ul>

app/views/trips/edit.html.erb
<h1>
  Editing Trip
  <%= link_to 'Cancel', trip_path(@trip) %>
</h1>

<%= render 'form', trip: @trip %>
<%= link_to 'Delete', trip_path(@trip), method: :delete, data: { confirm: "Are you sure you want to delete #{@trip.title}?\nYou will lose all of the data associated with this trip." } %>

app/views/trips/edit.js.erb
$('.alert-container')
  .html("<%= escape_javascript (render partial: 'shared/dismissable_alert',
                                        locals: { message: @trip.errors.full_messages.join(',') } ) %>")

app/views/trips/index.html.erb
<%= react_component("Trips", {
  trips: @trips
}, tag: :span)%>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/new.js.erb
$('.alert-container')
  .html("<%= escape_javascript (render partial: 'shared/dismissable_alert',
                                        locals: { message: @trip.errors.full_messages.join(',') } ) %>")

app/views/trips/show.html.erb
<%= react_component "Trip", {trip: @presented_trip}, tag: :span %>